//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKR.GUI.LogixConnector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6666/WSProxy2/Connector.asmx")]
        public string JKR_GUI_LogixConnector_wsConnector_Connector {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_wsConnector_Connector"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.136/serviceportal/ws/BusinessService.asmx")]
        public string JKR_GUI_LogixConnector_BusinessService_BusinessServiceEvin_GUI_LogixConnector_BusinessService_BusinessService {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_BusinessService_BusinessServiceEvin_GUI_LogixConnector_Bus" +
                    "inessService_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.136/Gmb2b/ws/CertificateService.asmx")]
        public string JKR_GUI_LogixConnector_Cargob2bGM_CertificateService {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_Cargob2bGM_CertificateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.136/Gmlsc/ws/CertificateService.asmx")]
        public string JKR_GUI_LogixConnector_CertificateServiceGM_CertificateService {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_CertificateServiceGM_CertificateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.136/Gmlsc/ws/BusinessService.asmx")]
        public string JKR_GUI_LogixConnector_BusinessServiceGM_BusinessService {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_BusinessServiceGM_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.81/efile/FileService.asmx")]
        public string JKR_GUI_LogixConnector_eFileService_FileService {
            get {
                return ((string)(this["JKR_GUI_LogixConnector_eFileService_FileService"]));
            }
        }
    }
}
